# Generated by Django 4.0.2 on 2022-02-12 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=250)),
                ('country_code', models.CharField(max_length=250)),
                ('country_symbol', models.CharField(max_length=250)),
                ('created_on', models.DateField(auto_now=True)),
                ('deleted_on', models.DateField(auto_now=True)),
                ('update_on', models.DateField(auto_now=True)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Distric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distric_name', models.CharField(max_length=250)),
                ('created_on', models.DateField(auto_now=True)),
                ('deleted_on', models.DateField(auto_now=True)),
                ('update_on', models.DateField(auto_now=True)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Persnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_full_name', models.CharField(max_length=250)),
                ('p_moblie_number', models.CharField(max_length=250)),
                ('p_cnic', models.CharField(max_length=15)),
                ('created_on', models.DateField(auto_now=True)),
                ('deleted_on', models.DateField(auto_now=True)),
                ('update_on', models.DateField(auto_now=True)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tehsil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tehsil_name', models.CharField(max_length=250)),
                ('created_on', models.DateField(auto_now=True)),
                ('deleted_on', models.DateField(auto_now=True)),
                ('update_on', models.DateField(auto_now=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('distric_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.distric')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=250)),
                ('created_on', models.DateField(auto_now=True)),
                ('deleted_on', models.DateField(auto_now=True)),
                ('update_on', models.DateField(auto_now=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.country')),
            ],
        ),
        migrations.AddField(
            model_name='distric',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.province'),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=250)),
                ('b_address', models.CharField(max_length=250)),
                ('b_phone', models.CharField(max_length=250)),
                ('b_city', models.CharField(max_length=250)),
                ('b_pass', models.CharField(max_length=250)),
                ('created_on', models.DateField(auto_now=True)),
                ('deleted_on', models.DateField(auto_now=True)),
                ('update_on', models.DateField(auto_now=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('b_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.persnal')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=250)),
                ('created_on', models.DateField(auto_now=True)),
                ('deleted_on', models.DateField(auto_now=True)),
                ('update_on', models.DateField(auto_now=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('tehsil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.tehsil')),
            ],
        ),
    ]
