# Generated by Django 4.0.2 on 2022-02-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persnal',
            new_name='Personal',
        ),
    ]
